name: Release

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build/**'
      - '.github/workflows/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .prod.env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .prod.env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .prod.env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .prod.env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .prod.env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .prod.env
          echo "GOOGLE_SEARCH_API_KEY=${{ secrets.GOOGLE_SEARCH_API_KEY }}" >> .prod.env
          echo "GOOGLE_SEARCH_ENGINE_ID=${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}" >> .prod.env
          cp .prod.env build/.env

      - name: Build
        run: pnpm release

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          PROJECT_ROOT: ${{ secrets.PROJECT_ROOT }}
          TARGET: ${{ secrets.TARGET }}
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "build"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            echo "before"
          SCRIPT_AFTER: |
            cp "$TARGET/.env" "$PROJECT_ROOT/.env"
            ~/bin/restartBBBot.sh
